### ISSUE TITLE
Service Control Policy Syntax Doesn't Mention Conditions

### ISSUE THREAD

**Issue by joelthompson** [awsdocs/aws-organizations-docs#3]
The [Service Control Policy Syntax](https://github.com/awsdocs/aws-organizations-docs/blob/a2ebe5450d5acf39aefe13eba547cde459c714d4/doc_source/orgs_reference_scp-syntax.md) guide doesn't refer to Conditions. I'm assuming that Conditions aren't supported, but it would be nice to have that called out explicitly.

**Comment by bisdavid** [comment]
Joel,
Thanks for reporting this.  Yes, it was indeed an oversight. Principal is the same way, but I included it. I have now fixed it in the source code of the file, and it will be live later today.  I'll get the github version of the source updated to include it later this week as well.  Thanks!
