### ISSUE TITLE
Document throttling limits for AWS Organizations

### ISSUE THREAD

**Issue by iainelder** [awsdocs/aws-organizations-docs#39]
The DescribeAccount API is throttled such that if there are multiple threads calling the API in a single account then some throttling errors may be observed (see https://github.com/connelldave/botocove/issues/12 for an example use case).

> `TooManyRequestsException: An error occurred (TooManyRequestsException) when calling the DescribeAccount operation (reached max retries: 4): AWS Organizations can't complete your request because another request is already in progress. Try again later.`

I can't find any documentation about the throttling limit for any Organizations APIs.

The information is available for the Security Hub service on the [welcome page of the API reference](https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html).

> The following throttling limits apply to using Security Hub API operations.
>
> * BatchEnableStandards - RateLimit of 1 request per second, BurstLimit of 1 request per second.
> * GetFindings - RateLimit of 3 requests per second. BurstLimit of 6 requests per second.
> [...]

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
