### ISSUE TITLE
Make it obvious that SCPs are evaluated slightly differently from normal IAM policies

### ISSUE THREAD

**Issue by copumpkin** [awsdocs/aws-organizations-docs#4]
On [this page on SCPs](https://github.com/awsdocs/aws-organizations-docs/blob/a2ebe5450d5acf39aefe13eba547cde459c714d4/doc_source/orgs_reference_scp-syntax.md#action-element), you say:

> The wildcard can appear only by itself or at the very end of the string. `"*"` or `"ec2:Describe*"` are both valid, while `"iam:*User"` is not valid.

This is a definite departure from how `"Action"` values are evaluated elsewhere, as evidenced by the example in [this IAM page](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_action.html):

> You can also use wildcards (*) as part of the action name. For example, the following Action element applies to all IAM actions that include the string AccessKey, including CreateAccessKey, DeleteAccessKey, ListAccessKeys, and UpdateAccessKey.
>
>     "Action": "iam:*AccessKey*"

This distinction probably makes sense, but considering how hard it is for users to reason about IAM policies (or to notice that their policies are subtly wrong), it might be good to put a loud note making it clear that this is a clear departure from what they might be used to from other IAM policies.

**Comment by copumpkin** [comment]
I guess on further inspection, the API does actually prevent me from creating a policy with bad wildcards, with the not-entirely-helpful message:

```
An error occurred (MalformedPolicyDocumentException) when calling the UpdatePolicy operation: The provided policy document does not meet the requirements of the specified policy type.
```

So perhaps it's not quite as important to document this distinction. I do think it's good to point out "false friends" in documentation though, so I'll leave this open.

**Comment by bisdavid** [comment]
Thanks for the feedback.  I'll consider strengthening that message of difference with IAM a bit.

**Comment by bisdavid** [comment]
Improved here: https://github.com/awsdocs/aws-organizations-docs/blob/master/doc_source/orgs_reference_scp-syntax.md#action-element
and here:https://github.com/awsdocs/aws-organizations-docs/blob/master/doc_source/orgs_permissions_iam-policies.md#granting-limited-access-by-actions

**Comment by copumpkin** [comment]
Thanks!

**Comment by ghost** [comment]
**Observation from my side:**
[Documentation](https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_policies_example-scps.html#example-require-tag-on-create), last example _Example 13: Require a Tag Upon Resource Creation_ uses wildcard in a format that it is not supposed to be allowed `"arn:aws:ec2:*:*:instance/*"`

I tried to create policy through AWS CLI and it fails with the error reported here.
`An error occurred (MalformedPolicyDocumentException) when calling the UpdatePolicy operation: The provided policy document does not meet the requirements of the specified policy type.`

However when I create policy via AWS Management console it is possible to create it without any problems.
